In [6]:
import pymc3 as pm
import numpy as np

In [20]:
with pm.Model() as model:
    age = pm.Normal("age", 10, 100, shape=10)
    output = pm.Deterministic("output", pm.math.sum(age)/10)
    observation = pm.Normal("observation", age > 50, 0.00001, observed=1)
    trace = pm.sample(100, tune=5000)

<ipython-input-20-7f919869279e>:5: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  trace = pm.sample(100, tune=5000)
Only 100 samples in chain.
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [age]


Sampling 2 chains for 5_000 tune and 100 draw iterations (10_000 + 200 draws total) took 15 seconds.
The chain contains only diverging samples. The model is probably misspecified.
The chain contains only diverging samples. The model is probably misspecified.
The acceptance probability does not match the target. It is 0.6596535989339029, but should be close to 0.8. Try to increase the number of tuning steps.
The rhat statistic is larger than 1.4 for some parameters. The sampler did not converge.
The number of effective samples is smaller than 10% for some parameters.


In [21]:
trace["output"]

array([ -10.48333097,  -10.20042317,  -10.04898343,  -10.04898343,
        -10.04898343,  -10.04898343,  -12.26671775,  -12.26671775,
        -10.73541399,  -10.73541399,   -8.93309019,   -7.21501862,
        -12.79587408,  -16.0695367 ,  -14.95515897,  -14.79959219,
        -14.79959219,  -14.79959219,  -14.79959219,  -14.79959219,
        -15.06967704,  -14.11379727,  -21.21875102,  -16.9844834 ,
        -18.16323097,  -17.73614971,  -25.07880967,  -30.55094371,
        -37.07322185,  -26.86909509,  -26.86909509,  -26.16596046,
        -26.51225941,  -36.31567529,  -48.26793051,  -41.79815921,
        -83.73173997,  -75.3799204 ,  -70.62039583,  -70.44900881,
        -57.69934993,  -55.33623019,  -67.555549  ,  -61.93765903,
        -55.18243275,  -56.18056238,  -63.0451804 ,  -60.29362752,
        -67.40056182,  -79.7811195 ,  -69.07876539,  -69.47398295,
        -69.36254872,  -79.68176249,  -71.73847771,  -73.14641453,
        -69.35292689,  -66.92383651,  -68.01063022,  -77.52437

In [23]:
with pm.Model() as model:
    age = pm.Normal("age", 10, 2, shape=10, testval=[11.5]*10)
    output = pm.Deterministic("output", pm.math.sum(age)/10)
    cons = pm.Deterministic("cons", output)
    observation = pm.Bernoulli("observation", 1*((output > 11.)), observed=1)
    observation2 = pm.Bernoulli("observation2", 1*(12 > observation), observed=1)
    
    trace = pm.sample(1000)

<ipython-input-23-6c182117d8fd>:8: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  trace = pm.sample(1000)
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [age]


Sampling 2 chains for 1_000 tune and 1_000 draw iterations (2_000 + 2_000 draws total) took 14 seconds.
There were 999 divergences after tuning. Increase `target_accept` or reparameterize.
The chain contains only diverging samples. The model is probably misspecified.
The rhat statistic is larger than 1.05 for some parameters. This indicates slight problems during sampling.
The estimated number of effective samples is smaller than 200 for some parameters.


In [28]:
trace["output"]

array([11.35612944, 11.55641948, 11.43567917, ..., 11.0106898 ,
       11.0926528 , 11.0926528 ])

In [2]:
cons = "s>10"
cons.replace(">","<")

's<10'

In [3]:
cons

's>10'

In [8]:
test = lambda a,b: None

In [9]:
test(1,2)
print("hello")

hello


In [10]:
l = [1,2,3,4,5]

In [11]:
l.index(2)

1

In [3]:
import privugger as pv
import numpy as np

def alpha(age):
    return (age.sum()) / (age.size)

#################
## AGE EXAMPLE ##
#################

# Database size
N    = 10

# Specify distributions
age  = pv.Normal(mu=10, std=3.5, num_elements=N)

# Create dataset. Refer to "age_alice" as "age1" in the trace and "age" as "age2" in the trace. This is the general naming convention. 
ds   = pv.Dataset(input_specs = [age],
                  var_names   = ["age"])

# For now output type can be: Int, Float, List(Float), List(Int)
program = pv.Program(dataset=ds, output_type=pv.Float, method=alpha)

# Add observations
program.add_observation("57>output>56")

# Call infer and specify program output
trace = pv.infer(program, cores=2, draws=1000)

C:\Users\Mathias\Documents\dev\privugger\privugger\transformer\method.py:160: FutureWarning: In v4.0, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  trace = pm.sample(draws=draws, chains=chains, cores=cores)
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Initializing NUTS failed. Falling back to elementwise auto-assignment.
Multiprocess sampling (2 chains in 2 jobs)
Slice: [age]
Could not pickle model, sampling singlethreaded.
Sequential sampling (2 chains in 1 job)
Slice: [age]


Sampling 2 chains for 1_000 tune and 1_000 draw iterations (2_000 + 2_000 draws total) took 11 seconds.


In [4]:
trace["output"]

array([ 7.9738064 ,  9.3916857 , 11.8016758 , ...,  9.26487021,
       10.05119467,  9.68262933])

In [15]:
print(all(np.array(trace["output"] < 56).flatten()))

True
